
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE registrations CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE events CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100),
    full_name VARCHAR2(100),
    contact_number VARCHAR2(15),
    email VARCHAR2(100),
    role VARCHAR2(20) DEFAULT 'STUDENT',
    status VARCHAR2(20) DEFAULT 'PENDING'
);


CREATE TABLE events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    event_date DATE,
    venue VARCHAR2(100)
);


CREATE TABLE registrations (
    reg_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) REFERENCES users(username) ON DELETE CASCADE,
    event_id NUMBER REFERENCES events(event_id) ON DELETE CASCADE,
    reg_date DATE DEFAULT SYSDATE
);


INSERT INTO events (title, description, event_date, venue) 
VALUES ('Campus Tech Hackathon 2026', 'An overnight coding and software innovation challenge for university students.', TO_DATE('2026-10-15', 'YYYY-MM-DD'), 'Main Auditorium');

INSERT INTO events (title, description, event_date, venue) 
VALUES ('AI and Machine Learning Workshop', 'Hands-on session exploring modern artificial intelligence frameworks.', TO_DATE('2026-10-20', 'YYYY-MM-DD'), 'Lab 3 - IT Block');

COMMIT;


--  Create a PL/SQL Stored Procedure to get event registration count
CREATE OR REPLACE PROCEDURE get_event_reg_count (
    p_event_id IN NUMBER,
    p_total_count OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*) 
    INTO p_total_count 
    FROM registrations 
    WHERE event_id = p_event_id;
EXCEPTION
    WHEN OTHERS THEN
        p_total_count := 0;
END;
/

-- Add price column to events table if not exists
ALTER TABLE events ADD price NUMBER(10, 2) DEFAULT 0;

-- Update sample events with ticket prices
UPDATE events SET price = 1500 WHERE event_id = 1;
UPDATE events SET price = 2500 WHERE event_id = 2;
COMMIT;

